### ISSUE TITLE
Use WGS84 instead of WGS72

### ISSUE THREAD

**Issue by davidtgillard** [dnwrnr/sgp4#15]
Hi,

I noticed that the parameters for earth semi-major axis and flattening are for the WGS72 datum. Can it be changed to WGS84, since this is now the more common reference? Alternatively, is it possible to accommodate the ability to choose the datum at run time?

Thanks for this great library.

**Comment by cx1011** [comment]
so bro，have you done it  and how to transfer

**Comment by jriesen** [comment]
Note that the Python SGP4 implementation - which is an extremely close port of the official C++ version - strongly recommends sticking with WGS72 instead of WGS84, see https://pypi.org/project/sgp4/#gravity

> The most recent official paper on SGP4 [...] specifies that “We use WGS-72 as the default value”, so this Python module uses the same default.

> You will in general get less accurate results if you choose WGS-84. Even though it reflects more recent and accurate measures of the Earth, satellite TLEs across the industry are most likely generated with WGS-72 as their basis. The positions you generate will better agree with the real positions of each satellite if you use the same underlying gravity constants as were used to generate the TLE.

Nevertheless, by reviewing the C++ source code from the original SGP4 author at http://celestrak.org/publications/AIAA/2006-6753/ as well as the Python module, I believe one only needs to modify the five following contents in `Globals.h` here to convert to WGS-84:

```cpp
// WGS-84
const double kMU = 398600.5;
const double kXKMPER = 6378.137;
const double kXJ2 = 1.08262998905e-3;
const double kXJ3 = -2.53215306e-6;
const double kXJ4 = -1.61098761e-6;
```

However, as mentioned above it seems like it might be a good idea to stick with WGS72 for propagation.

Now considering converting from ECI to geodetic: the only constant in `Eci.cc` that seems affected by choice of datum is the mean equatorial radius `kXKMPER` which differ by 2m.  (The flattening constant kF is the same value, 1/298.26, in both WGS72 and WGS84.)  This will cause the latitude and altitude to be off very slightly from WGS84 (roughly 2m for altitude), but one could compensate by providing the WGS84 radius to `Eci::ToGeodetic()` if desired.

**Comment by davidtgillard** [comment]
@jriesen I agree that WGS72 should be the default, given the context of typical use of SGP4. In retrospect this issue should have been stated to add the ability to specify different earth models. 

I had requirements to support WGS84, but ended up using/modifying a different library. Given that this issue hasn't attracted any activity and it's not longer of any relevance to me, I will close it as stale.
